version: '3.7'

services:
    db:
        container_name: postgres
        image: postgres:15.2
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - 5433:5432
        networks:
            - bogd-stream-backend
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
        driver: local
networks:
    bogd-stream-backend:
        driver: bridge
