version: '3.7'

services:
    db:
        container_name: postgres
        image: postgres:15.2
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '5433:5432'
        networks:
            - bogd-stream-backend
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        container_name: redis
        image: redis:7-alpine
        restart: always
        command: ['redis-server', '--appendonly', 'yes']
        ports:
            - '6379:6379'
        networks:
            - bogd-stream-backend
        volumes:
            - redis_data:/data
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 5s
            timeout: 3s
            retries: 10

    redisinsight:
        container_name: redisinsight
        image: redis/redisinsight:latest
        restart: always
        ports:
            - '5540:5540' # UI будет доступен на http://localhost:5540
        networks:
            - bogd-stream-backend
        depends_on:
            - redis
        volumes:
            - redisinsight_data:/data

volumes:
    postgres_data:
        driver: local
    redis_data:
        driver: local
    redisinsight_data:
        driver: local

networks:
    bogd-stream-backend:
        driver: bridge
